from _pytest.config import Config as Config
from typing import List, Optional, Text, Union

class AgentConfig:
    _rp_rerun: Optional[bool] = ...
    pconfig: Config = ...
    rp_endpoint: Text = ...
    rp_hierarchy_code: bool = ...
    rp_dir_level: int = ...
    rp_hierarchy_dirs: bool = ...
    rp_dir_path_separator: str = ...
    rp_ignore_attributes: set = ...
    rp_is_skipped_an_issue: bool = ...
    rp_issue_id_marks: bool = ...
    rp_issue_system_url: str = ...
    rp_launch: Text = ...
    rp_launch_id: Optional[Text] = ...
    rp_launch_attributes: Optional[List] = ...
    rp_launch_description: Text = ...
    rp_log_batch_size: int = ...
    rp_log_level: Optional[int] = ...
    rp_mode: str = ...
    rp_parent_item_id: Optional[Text] = ...
    rp_project: Text = ...
    rp_rerun_of: Optional[Text] = ...
    rp_retries: int = ...
    rp_skip_connection_test: bool = ...
    rp_uuid: Text = ...
    rp_verify_ssl: bool = ...

    def __init__(self, pytest_config: Config) -> None: ...

    def find_option(self, pytest_config, param: str) -> Union[str, bool, list]: ...
