from logging import Logger
from typing import Text

import pytest

from .config import AgentConfig
from _pytest.config import Config
from _pytest.config.argparsing import Parser
from _pytest.main import Session
from reportportal_client import RPClient
from xdist.workermanage import WorkerController

log: Logger
MANDATORY_PARAMETER_MISSED_PATTERN: Text
FAILED_LAUNCH_WAIT: Text

def check_connection(agent_config: AgentConfig) -> bool: ...
def is_control(config: Config) -> bool: ...
def wait_launch(rp_client: RPClient) -> bool: ...
def pytest_configure_node(node: WorkerController) -> None: ...
def pytest_sessionstart(session: Session) -> None: ...
def pytest_collection_finish(session: Session) -> None: ...
def pytest_sessionfinish(session: Session) -> None: ...
def pytest_configure(config: Config) -> None: ...
def pytest_runtest_protocol(item: pytest.Item) -> None: ...
def pytest_runtest_makereport(item: pytest.Item) -> None: ...
def pytest_addoption(parser: Parser) -> None: ...
