from logging import Logger
from .config import AgentConfig as AgentConfig
from .listener import RPReportListener as RPReportListener
from .service import PyTestServiceClass as PyTestServiceClass
from _pytest.config import Config as Config
from _pytest.config.argparsing import Parser as Parser
from _pytest.main import Session as Session
from pytest_reportportal import LAUNCH_WAIT_TIMEOUT as LAUNCH_WAIT_TIMEOUT
from reportportal_client.service import ReportPortalService as ReportPortalService
from xdist.workermanage import WorkerController as WorkerController

log: Logger

def check_connection(aconf: AgentConfig) -> None: ...
def is_master(config: Config) -> bool: ...
def wait_launch(rp_client: ReportPortalService) -> None: ...
def pytest_configure_node(node: WorkerController) -> None: ...
def pytest_sessionstart(session: Session) -> None: ...
def pytest_collection_finish(session: Session) -> None: ...
def pytest_sessionfinish(session: Session) -> None: ...
def pytest_configure(config: Config) -> None: ...
def pytest_unconfigure(config: Config) -> None: ...
def pytest_addoption(parser: Parser) -> None: ...
